name: smart_note
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  provider: ^6.1.1
  flutter_quill: ^9.3.10
  flutter_local_notifications: ^17.0.0
  local_auth: ^2.2.0
  encrypt: ^5.0.3
  shared_preferences: ^2.2.2
  flutter_staggered_animations: ^1.1.1
  google_mobile_ads: ^5.0.0
  in_app_purchase: ^3.1.11
  share_plus: ^9.0.0
  url_launcher: ^6.2.5
  intl: ^0.19.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
